# Generated by Django 5.2a1 on 2025-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="birth",
            new_name="birth_date",
        ),
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
